crm/urls.py
import os
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views
from django.urls import include, path
from django.urls import re_path as url
from django.views.generic import TemplateView
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)
# from drf_yasg import openapi
# from drf_yasg.views import get_schema_view
from rest_framework import permissions
from wagtail import urls as wagtail_urls
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.documents import urls as wagtaildocs_urls

app_name = "crm"

urlpatterns = [
    url(
        r"^healthz/$",
        TemplateView.as_view(template_name="healthz.html"),
        name="healthz",
    ),
    path("api/", include("common.app_urls", namespace="common_urls")),
    path(
        "logout/", views.LogoutView.as_view(), {"next_page": "/login/"}, name="logout"
    ),
    path("admin/", include(wagtailadmin_urls)),
    
    path("django/admin/", admin.site.urls),
    path("documents/", include(wagtaildocs_urls)),
    path("schema/", SpectacularAPIView.as_view(), name="schema"),
    # Optional UI:
    path(
        "swagger-ui/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
    path(
        "api/schema/redoc/",
        SpectacularRedocView.as_view(url_name="schema"),
        name="redoc",
    ),
    path("", include(wagtail_urls)),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # urlpatterns = urlpatterns + static(
    #     settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    # )

opportunity/urls.py
from django.urls import path

from opportunity import views

app_name = "api_opportunities"

urlpatterns = [
    path("", views.OpportunityListView.as_view()),
    path("<str:pk>/", views.OpportunityDetailView.as_view()),
    path("comment/<str:pk>/", views.OpportunityCommentView.as_view()),
    path("attachment/<str:pk>/", views.OpportunityAttachmentView.as_view()),
]

oppurtunity/urls.py
from django.conf.urls import url
from oppurtunity import views

app_name = 'oppurtunity'


urlpatterns = [
    url(r'^list/$', views.opp_list, name='list'),
    url(r'^create/$', views.opp_create, name='save'),
    url(r'^(?P<pk>\d+)/view/$', views.opp_view, name='opp_view'),
    url(r'^(?P<pk>\d+)/edit/$', views.opp_edit, name='opp_edit'),
    url(r'^(?P<pk>\d+)/delete/$', views.opp_remove, name='opp_remove'),
    url(r'^contacts/$', views.contacts, name='contacts'),
    url(r'^get/list/$', views.get_opportunity, name='get_opportunity'),
    # comments
    url(r'^comment/add/$', views.add_comment, name='add_comment'),
    url(r'^comment/edit/$', views.edit_comment, name='edit_comment'),
    url(r'^comment/remove/$', views.remove_comment, name='remove_comment'),
]

opportunity/models.py
import arrow
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.utils.translation import pgettext_lazy

from accounts.models import Account, Tags
from common.models import Org, Profile
from common.base import BaseModel
from common.utils import CURRENCY_CODES, SOURCES, STAGES
from contacts.models import Contact
from teams.models import Teams


class Opportunity(BaseModel):
    name = models.CharField(pgettext_lazy("Name of Opportunity", "Name"), max_length=64)
    account = models.ForeignKey(
        Account,
        related_name="opportunities",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )
    stage = models.CharField(
        pgettext_lazy("Stage of Opportunity", "Stage"), max_length=64, choices=STAGES
    )
    currency = models.CharField(
        max_length=3, choices=CURRENCY_CODES, blank=True, null=True
    )
    amount = models.DecimalField(
        _("Opportunity Amount"), decimal_places=2, max_digits=12, blank=True, null=True
    )
    lead_source = models.CharField(
        _("Source of Lead"), max_length=255, choices=SOURCES, blank=True, null=True
    )
    probability = models.IntegerField(default=0, blank=True, null=True)
    contacts = models.ManyToManyField(Contact)
    closed_by = models.ForeignKey(
        Profile,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="oppurtunity_closed_by",
    )
    # closed_on = models.DateTimeField(blank=True, null=True)
    closed_on = models.DateField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    assigned_to = models.ManyToManyField(
        Profile, related_name="opportunity_assigned_to"
    )
    is_active = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tags, blank=True)
    teams = models.ManyToManyField(Teams, related_name="oppurtunity_teams")
    org = models.ForeignKey(
        Org,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="oppurtunity_org",
    )

    class Meta:
        verbose_name = "Opportunity"
        verbose_name_plural = "Opportunities"
        db_table = "opportunity"
        ordering = ("-created_at",)

    def __str__(self):
        return f"{self.name}"

    @property
    def created_on_arrow(self):
        return arrow.get(self.created_at).humanize()

    @property
    def get_team_users(self):
        team_user_ids = list(self.teams.values_list("users__id", flat=True))
        return Profile.objects.filter(id__in=team_user_ids)

    @property
    def get_team_and_assigned_users(self):
        team_user_ids = list(self.teams.values_list("users__id", flat=True))
        assigned_user_ids = list(self.assigned_to.values_list("id", flat=True))
        user_ids = team_user_ids + assigned_user_ids
        return Profile.objects.filter(id__in=user_ids)

    @property
    def get_assigned_users_not_in_teams(self):
        team_user_ids = list(self.teams.values_list("users__id", flat=True))
        assigned_user_ids = list(self.assigned_to.values_list("id", flat=True))
        user_ids = set(assigned_user_ids) - set(team_user_ids)
        return Profile.objects.filter(id__in=list(user_ids))

oppurtunity/forms.py
from django import forms
from oppurtunity.models import Opportunity
from common.models import Comment


class OpportunityForm(forms.ModelForm):
    probability = forms.IntegerField(max_value=100, required=False)

    def __init__(self, *args, **kwargs):
        assigned_users = kwargs.pop('assigned_to', [])
        opp_accounts = kwargs.pop('account', [])
        opp_contacts = kwargs.pop('contacts', [])
        super(OpportunityForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs = {"class": "form-control"}
        self.fields['description'].widget.attrs.update({
            'rows': '8'})
        self.fields['assigned_to'].queryset = assigned_users
        self.fields['account'].queryset = opp_accounts
        self.fields['contacts'].queryset = opp_contacts
        self.fields['assigned_to'].required = False
        self.fields['teams'].required = False
        self.fields['contacts'].required = False

    class Meta:
        model = Opportunity
        fields = (
            'name', 'amount', 'account', 'contacts', 'assigned_to', 'currency',
            'probability', 'teams', 'closed_on', 'lead_source', 'description', 'stage',
        )


class OpportunityCommentForm(forms.ModelForm):
    comment = forms.CharField(max_length=64, required=True)

    class Meta:
        model = Comment
        fields = ('comment', 'opportunity', 'commented_by')

opportunity/views.py
import json

from django.db.models import Q
from drf_spectacular.utils import OpenApiExample, OpenApiParameter, extend_schema
from rest_framework import status
from rest_framework.pagination import LimitOffsetPagination
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from accounts.models import Account, Tags
from accounts.serializer import AccountSerializer, TagsSerailizer
from common.models import Attachments, Comment, Profile

#from common.external_auth import CustomDualAuthentication
from common.serializer import (
    AttachmentsSerializer,
    CommentSerializer,
    ProfileSerializer,
)
from common.utils import CURRENCY_CODES, SOURCES, STAGES
from contacts.models import Contact
from contacts.serializer import ContactSerializer
from opportunity import swagger_params1
from opportunity.models import Opportunity
from opportunity.serializer import *
from opportunity.tasks import send_email_to_assigned_user
from teams.models import Teams


class OpportunityListView(APIView, LimitOffsetPagination):

    #authentication_classes = (CustomDualAuthentication,)
    permission_classes = (IsAuthenticated,)
    model = Opportunity

    def get_context_data(self, **kwargs):
        params = self.request.query_params
        queryset = self.model.objects.filter(org=self.request.profile.org).order_by("-id")
        accounts = Account.objects.filter(org=self.request.profile.org)
        contacts = Contact.objects.filter(org=self.request.profile.org)
        if self.request.profile.role != "ADMIN" and not self.request.user.is_superuser:
            queryset = queryset.filter(
                Q(created_by=self.request.profile.user) | Q(assigned_to=self.request.profile)
            ).distinct()
            accounts = accounts.filter(
                Q(created_by=self.request.profile.user) | Q(assigned_to=self.request.profile)
            ).distinct()
            contacts = contacts.filter(
                Q(created_by=self.request.profile.user) | Q(assigned_to=self.request.profile)
            ).distinct()

        if params:
            if params.get("name"):
                queryset = queryset.filter(name__icontains=params.get("name"))
            if params.get("account"):
                queryset = queryset.filter(account=params.get("account"))
            if params.get("stage"):
                queryset = queryset.filter(stage__contains=params.get("stage"))
            if params.get("lead_source"):
                queryset = queryset.filter(
                    lead_source__contains=params.get("lead_source")
                )
            if params.get("tags"):
                queryset = queryset.filter(
                    tags__in=params.get("tags")
                ).distinct()

        context = {}
        results_opportunities = self.paginate_queryset(
            queryset.distinct(), self.request, view=self
        )
        opportunities = OpportunitySerializer(results_opportunities, many=True).data
        if results_opportunities:
            offset = queryset.filter(id__gte=results_opportunities[-1].id).count()
            if offset == queryset.count():
                offset = None
        else:
            offset = 0
        context["per_page"] = 10
        page_number = (int(self.offset / 10) + 1,)
        context["page_number"] = page_number
        context.update(
            {
                "opportunities_count": self.count,
                "offset": offset,
            }
        )
        context["opportunities"] = opportunities
        context["accounts_list"] = AccountSerializer(accounts, many=True).data
        context["contacts_list"] = ContactSerializer(contacts, many=True).data
        context["tags"] = TagsSerailizer(Tags.objects.filter(), many=True).data
        context["stage"] = STAGES
        context["lead_source"] = SOURCES
        context["currency"] = CURRENCY_CODES

        return context

    @extend_schema(
        tags=["Opportunities"],
        parameters=swagger_params1.opportunity_list_get_params,
    )
    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        return Response(context)

    @extend_schema(
        tags=["Opportunities"],
        parameters=swagger_params1.organization_params,request=OpportunityCreateSwaggerSerializer
    )
    def post(self, request, *args, **kwargs):
        params = request.data
        serializer = OpportunityCreateSerializer(data=params, request_obj=request)
        if serializer.is_valid():
            opportunity_obj = serializer.save(
                created_by=request.profile.user,
                closed_on=params.get("due_date"),
                org=request.profile.org,
            )

            if params.get("contacts"):
                contacts_list = params.get("contacts")
                contacts = Contact.objects.filter(id__in=contacts_list, org=request.profile.org)
                opportunity_obj.contacts.add(*contacts)

            if params.get("tags"):
                tags = params.get("tags")
                for tag in tags:
                    obj_tag = Tags.objects.filter(slug=tag.lower())
                    if obj_tag.exists():
                        obj_tag = obj_tag[0]
                    else:
                        obj_tag = Tags.objects.create(name=tag)
                    opportunity_obj.tags.add(obj_tag)

            if params.get("stage"):
                stage = params.get("stage")
                if stage in ["CLOSED WON", "CLOSED LOST"]:
                    opportunity_obj.closed_by = self.request.profile

            if params.get("teams"):
                teams_list = params.get("teams")
                teams = Teams.objects.filter(id__in=teams_list, org=request.profile.org)
                opportunity_obj.teams.add(*teams)

            if params.get("assigned_to"):
                assinged_to_list = params.get("assigned_to")
                profiles = Profile.objects.filter(
                    id__in=assinged_to_list, org=request.profile.org, is_active=True
                )
                opportunity_obj.assigned_to.add(*profiles)

            if self.request.FILES.get("opportunity_attachment"):
                attachment = Attachments()
                attachment.created_by = self.request.profile.user
                attachment.file_name = self.request.FILES.get(
                    "opportunity_attachment"
                ).name
                attachment.opportunity = opportunity_obj
                attachment.attachment = self.request.FILES.get("opportunity_attachment")
                attachment.save()

            recipients = list(
                opportunity_obj.assigned_to.all().values_list("id", flat=True)
            )

            send_email_to_assigned_user.delay(
                recipients,
                opportunity_obj.id,
            )
            return Response(
                {"error": False, "message": "Opportunity Created Successfully"},
                status=status.HTTP_200_OK,
            )

        return Response(
            {"error": True, "errors": serializer.errors},
            status=status.HTTP_400_BAD_REQUEST,
        )


class OpportunityDetailView(APIView):
    #authentication_classes = (CustomDualAuthentication,)
    permission_classes = (IsAuthenticated,)
    model = Opportunity

    def get_object(self, pk):
        return self.model.objects.filter(id=pk).first()

    @extend_schema(
        tags=["Opportunities"],
        parameters=swagger_params1.organization_params,request=OpportunityCreateSwaggerSerializer
    )
    def put(self, request, pk, format=None):
        params = request.data
        opportunity_object = self.get_object(pk=pk)
        if opportunity_object.org != request.profile.org:
            return Response(
                {"error": True, "errors": "User company doesnot match with header...."},
                status=status.HTTP_403_FORBIDDEN,
            )
        if self.request.profile.role != "ADMIN" and not self.request.user.is_superuser:
            if not (
                (self.request.profile == opportunity_object.created_by)
                or (self.request.profile in opportunity_object.assigned_to.all())
            ):
                return Response(
                    {
                        "error": True,
                        "errors": "You do not have Permission to perform this action",
                    },
                    status=status.HTTP_403_FORBIDDEN,
                )

        serializer = OpportunityCreateSerializer(
            opportunity_object,
            data=params,
            request_obj=request,
            # opportunity=True,
        )

        if serializer.is_valid():
            opportunity_object = serializer.save(closed_on=params.get("due_date"))
            previous_assigned_to_users = list(
                opportunity_object.assigned_to.all().values_list("id", flat=True)
            )
            opportunity_object.contacts.clear()
            if params.get("contacts"):
                contacts_list = params.get("contacts")
                contacts = Contact.objects.filter(id__in=contacts_list, org=request.profile.org)
                opportunity_object.contacts.add(*contacts)

            opportunity_object.tags.clear()
            if params.get("tags"):
                tags = params.get("tags")
                for tag in tags:
                    obj_tag = Tags.objects.filter(slug=tag.lower())
                    if obj_tag.exists():
                        obj_tag = obj_tag[0]
                    else:
                        obj_tag = Tags.objects.create(name=tag)
                    opportunity_object.tags.add(obj_tag)

            if params.get("stage"):
                stage = params.get("stage")
                if stage in ["CLOSED WON", "CLOSED LOST"]:
                    opportunity_object.closed_by = self.request.profile

templates/oppurtunity/opportunities_list.html
<table class="table">
  <thead>
    <tr>
      <th width="50%">
        <a href='#'>
        Name
        </a>
        <span class="caret"></span>
      </th>
      <th>
        <a href="#">
        Stage
        </a>
      </th>
    </tr>
  </thead>
  <tbody>
    {% ifequal opportunities|length  0 %}
    <tr>
      <td class="cell">
        NO OPPORTUNITIES FOUND!!
      </td>
    </tr>
    {% endifequal %}
    {% for opportunity in opportunities %}
    <tr>
      <td class="cell">
        <a class="cell parentname" id="{{ opportunity.id }}">
        {{ opportunity.name }}
        </a>
      </td>
      <td class="cell parentstage">
        {{ opportunity.stage }}
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

templates/oppurtunity/view_opportunity.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block breadcrumb1 %}
<!-- Breadcrumb Starts Here -->
  <ol class="breadcrumb">
    <li><a href="{% url 'oppurtunities:list' %}">OPPORTUNITIES</a></li>
    <li class="active">VIEW</li>
  </ol>
<!-- Breadcrumb Ends Here -->
{% endblock%}
{% block content%}
<!-- OPPORTUNITY VIEW STARTS -->
  <div class="main_container" id="maincontainer">
    <div class="overview_form_block row marl">
      <div class="col-md-8">
        <div class="panel panel-default">
          <div class="panel-heading view-pad">
            <h5>
              OVERVIEW
              <span class="pull-right" style="margin-top: -10px">
                <div class="dropdown">
                  <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Actions
                  <span class="caret"></span></button>
                  <ul class="dropdown-menu">
                    <li><a href="{% url 'oppurtunities:opp_edit' opportunity_record.id %}" >Edit</a></li>
                    <li class="delete_contact"><a href="{% url 'oppurtunities:opp_remove' opportunity_record.id %}" id="remove_contact">REMOVE</a></li>
                  </ul>
                </div>
              </span>
            </h5>
          </div>
          <div class="panel-content" id="datashow">
            <div class="row marl">
              <div class="col-md-6">
                <div class="filter_col col-md-12" id="iname">
                  <div class="form-group">
                    <label class="opportunity_field_label" for="id_name" data-name="name">Name</label>
                    <div class="opportunity_field" id="opportunity_name" data-name="name">{{ opportunity_record.name }}</div>
                  </div>
                </div>
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label class="opportunity_field_label" for="id_opportunity_account" data-name="name">Account</label>
                    <div class="opportunity_field" id ="opportunity_account" data-name="name">{{ opportunity_record.account }}</div>
                  </div>
                </div>
                <div class="filter_col col-md-12">
                  {% if opportunity_record.contacts.all %}
                  <div class="form-group">
                    <label class="opportunity_field_label" for="id_contact" data-name="name">Contact(s)</label>
                    <div class="opportunity_field" id="opportunity_contact" data-name="name">
                      {% for contact in opportunity_record.contacts.all %}
                        <li>{{ contact }}</li>
                      {% endfor %}
                    </div>
                  </div>
                  {% endif %}
                </div>
                <div class="filter_col col-md-12">
                  {% if opportunity_record.amount %}
                  <div class="form-group">
                    <label class="opportunity_field_label" for="id_amount" data-name="name">Amount</label>
                    <div class="opportunity_field" id="opportunity_amount" data-name="name">{{ opportunity_record.currency }} {{ opportunity_record.amount }}</div>
                  </div>
                  {% endif %}
                </div>
              </div>
              <div class="col-md-4">
                <div class="filter_col col-md-12">
                  {% if opportunity_record.stage %}
                  <div class="form-group">
                    <label class="opportunity_field_label" for="id_stage" data-name="name">Stage</label>
                    <div class="opportunity_field" id="opportunity_stage" data-name="name">{{ opportunity_record.stage }}</div>
                  </div>
                  {% endif %}
                </div>
                <div class="filter_col col-md-12">
                  {% if opportunity_record.lead_source %}
                  <div class="form-group">
                    <label class="opportunity_field_label" for="id_lead_source" data-name="name">Lead Source</label>
                    <div class="opportunity_field" id="opportunity_lead_source" data-name="name">{{ opportunity_record.lead_source }}</div>
                  </div>
                  {% endif %}
                </div>
                <div class="filter_col col-md-12">
                  {% if opportunity_record.probability %}
                  <div class="form-group">
                    <label class="opportunity_field_label" for="id_probability" data-name="name">Probability</label>
                    <div class="opportunity_field" id="opportunity_probability" data-name="name">{{opportunity_record.probability}} %</div>
                  </div>
                  {% endif %}
                </div>
                <div class="filter_col col-md-12">
                  <div class="form-group">
                    <label class="opportunity_field_label" for="id_close_date" data-name="name">Close Date</label>
                    <div class="opportunity_field" id="opportunity_close_date" data-name="name">{{opportunity_record.closed_on|date}}</div>
                  </div>
                </div>
              </div>
              <div class="col-md-12">
                <div class="filter_col col-md-12">
                  {% if opportunity_record.description %}
                  <div class="form-group">
                    <label class="opportunity_field_label" for="id_description" data-name="name">Description</label>
                    <div class="opportunity_field" id="opportunity_description" data-name="name">{{opportunity_record.description}}</div>
                  </div>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
          <!-- Comments Section starts-->
          <div class="panel-heading view-pad">
            <h5>COMMENTS</h5>
          </div>
          <div class="panel-content" id="datashow">
            <div class="row marl">
              <div class="col-md-12">
                <form id="comment_form" method="POST" enctype="multipart/form-data">{% csrf_token %}
                  <div class="form-group">
                    <textarea class="form-control" textarea cols="40" rows="3" id="id_comments" name="comment" placeholder="Submit Your Comments Here"></textarea><span><i id="CommentError" style="display:none; color:red"></i></span>
                    </br>
                    <button class="btn btn-default save" style="text-align: center;" id="comment_submit" type="submit">Submit</button>
                  </div>
                  <input type="hidden" value="{{ opportunity_record.id }}" name="opportunityid">
                </form>
                <ul class="list-group" id="comments_div">
                  {% for comment in comments %}
                  <li class="list-group-item list-row" id="comment{{comment.id}}">
                    <div class="pull-right right-container">
                      <div class="list-row-buttons btn-group pull-right">
                        <button class="btn btn-link btn-sm dropdown-toggle" data-toggle="dropdown" type="button"><span class="caret"></span></button>
                        <ul class="dropdown-menu pull-right">
                          <li>
                            <a class="action" onclick="edit_comment({{comment.id}})">Edit</a>
                          </li>
                          <li>
                            <a class="action" onclick="remove_comment({{comment.id}})">Remove</a>
                          </li>
                        </ul>
                      </div>
                    </div>
                    <div class="stream-head-container">{{ comment.commented_by }} Commented</div>
                    <div class="stream-post-container" id="comment_name{{comment.id}}"><pre>{{ comment.comment }}</pre></div>
                    <div class="stream-date-container">{{ comment.commented_on }}</div>
                  </li>
                  {% endfor %}
                </ul>
              </div>
            </div>
            <div class="modal fade" id="Comments_Opportunity_Modal" role="dialog" data-keyboard="false" data-backdrop="static">
              <div class="modal-dialog modal-lg">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Update Your Comment</h4>
                  </div>
                  <form id="comment_edit_form" method="POST" >{% csrf_token %}
                    <div class="modal-body">
                      <div class="form-group">
                        <textarea class="form-control" textarea cols="40" rows="3" id="id_editcomment" name="comment" placeholder="Submit Your Comments"></textarea>
                        <input type="hidden" value="{{ opportunity.id }}" name="opportunityid">
                        <input type="hidden" value="" name="commentid" id="commentid">
                      </div>
                    </div>
                    <div class="modal-footer">
                      <button class="btn btn-default save" id="comment_edit" type="submit">Update</button>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
          <!-- Comments Section Ends-->
        </div>
      </div>
      <div class="col-md-4">
        <div class="panel panel-default">
          <div class="panel-heading view-pad">
            <h5>Label</h5>
          </div>
          <div class="panel-content" id="datashow">
            <div class="row marl">
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label class="opportunity_field_label" for="id_assigned_user" data-name="name">Assigned User(s)</label>
                  <div class="opportunity_field" id="opportunity_assigned_users" data-name="name">
                    {%if not opportunity_record.assigned_to %}
                      Not Assigned Yet
                    {% else %}
                      {% for user in opportunity_record.assigned_to.all %}
                        <li>{{ user }}</li>
                      {% endfor %}
                    {% endif %}
                  </div>
                </div>
              </div>
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label class="opportunity_field_label" for="id_team" data-name="name">Assigned Team(s)</label>
                  <div class="opportunity_field" id="opportunity_team" data-name="name">
                    {%if not opportunity_record.teams %}
                      Not Assigned Yet
                    {% else %}
                      {% for team in opportunity_record.teams.all %}
                        <li>{{ team }}</li>
                      {% endfor %}
                    {% endif %}
                  </div>
                </div>
              </div>
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label class="opportunity_field_label" for="id_created_on" data-name="name">Created On</label>
                  <div class="opportunity_field" id="opportunity_created_on" data-name="name">{{opportunity_record.created_on}}</div>
                </div>
              </div>
              <div class="filter_col col-md-12">
                <div class="form-group">
                  <label class="opportunity_field_label" for="id_created_by" data-name="name">Created by</label>
                  <div class="opportunity_field" id="opportunity_created_by" data-name="name">{{opportunity_record.created_by}}</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<!-- OPPORTUNITY VIEW ENDS -->
{% endblock %}
{% block js_block %}
<script src="{% static 'js/opportunities/view_opportunity.js' %}"></script>
<script type="text/javascript">
  $(function () {
      $('#datetimepicker1').datetimepicker({
          'format': 'YYYY-MM-DD',
      });
  });
</script>
{% endblock js_block %}